import Mathlib.Analysis.SpecialFunctions.Trigonometric.Basic
import Mathlib.Analysis.PSeries

/-!
# CONE_d: definitions (module L4 of the OQP 27B formalisation)

Authors: Ansh Mishra, Aryan Senthilkumar.  License: MIT.

This file defines the objects of the cone condition `CONE_d` exactly as in the certificate code
`iqoqi/programs/oqp27B_all/QD2/cells.py` (function `u_window`) and in `SHARED_LEMMAS.md` [QD2], QD2-L2:

* the Clausen function `Cl₂(θ) = ∑_{k ≥ 1} sin(kθ)/k²` (`OQP27.clausen2`);
* `N = 4d`, `G(u) = -(N²/(2π²)) Cl₂(2πu/N)` (`OQP27.coneG`) and `Ĝ(u) = G(u) + G(2d - u)` (`OQP27.coneGhat`);
* for a cell vector `ℓ = (ℓ₀, …, ℓ_{d-1})` (`ℓ_r ≥ 0`, `∑ ℓ_r = d`) the window sums
  `S_r(m) = ℓ_r + ⋯ + ℓ_{r+m-1}` (indices mod `d`, `OQP27.coneWindowSum`), the averages
  `P(m) = (1/d) ∑_{r<d} Ĝ(S_r(m))` (`OQP27.coneP`) and the cell direction
  `u^ℓ_m = P(m+1) - 2 P(m) + P(m-1)` (`OQP27.coneU`, used for `m = 1, …, d-1`);
* the DKZ multiplier vector `v_m = 2 csc(π m/(2d))` (`OQP27.coneV`);
* `OQP27.ConeCert d`: `v` lies in the convex cone generated by the cell directions, i.e. there are finitely
  many cells `ℓ^(k)` and weights `λ_k ≥ 0` with `∑_k λ_k u^{ℓ^(k)}_m = v_m` for `m = 1, …, d-1`.

Proved here: only the summability of the Clausen series (`OQP27.clausen2_summable`), which shows that
`clausen2` is the genuine Clausen function and not a junk value of `tsum`.

No hypotheses.  The mathematics (why `CONE_d` together with the strip inequality gives the optimality theorem)
is in `iqoqi/programs/oqp27B_all/QD2/LOG.md`, sections 1-4 (QD2-L1, QD2-L2, QD2-R1).

The skeleton file of module L1 did not exist when this file was written, so the definitions are made here, in
namespace `OQP27`, with names prefixed by `cone` to avoid clashes.
-/

namespace OQP27

open Real

/-- The Clausen function `Cl₂(θ) = ∑_{k ≥ 1} sin(k θ)/k²` (an absolutely convergent series). -/
noncomputable def clausen2 (θ : ℝ) : ℝ :=
  ∑' k : ℕ, Real.sin (((k : ℝ) + 1) * θ) / ((k : ℝ) + 1) ^ 2

/-- `G(u) = -(N²/(2π²)) Cl₂(2π u/N)` with `N = 4d`: a second antiderivative of `cot(π u/N)`. -/
noncomputable def coneG (d : ℕ) (u : ℝ) : ℝ :=
  -((4 * (d : ℝ)) ^ 2 / (2 * π ^ 2)) * clausen2 (2 * π * u / (4 * (d : ℝ)))

/-- `Ĝ(u) = G(u) + G(2d - u)`. -/
noncomputable def coneGhat (d : ℕ) (u : ℝ) : ℝ :=
  coneG d u + coneG d (2 * (d : ℝ) - u)

/-- The window sum `S_r(m) = ℓ_r + ℓ_{r+1} + ⋯ + ℓ_{r+m-1}` of a cell vector, indices taken mod `d`.
A cell vector is given as a function `ℕ → ℝ`; only the values `ℓ 0, …, ℓ (d-1)` are used. -/
def coneWindowSum (d : ℕ) (ell : ℕ → ℝ) (r m : ℕ) : ℝ :=
  ∑ i ∈ Finset.range m, ell ((r + i) % d)

/-- `P(m) = (1/d) ∑_{r < d} Ĝ(S_r(m))`. -/
noncomputable def coneP (d : ℕ) (ell : ℕ → ℝ) (m : ℕ) : ℝ :=
  (∑ r ∈ Finset.range d, coneGhat d (coneWindowSum d ell r m)) / d

/-- The cell direction `u^ℓ_m = Δ²_m P = P(m+1) - 2 P(m) + P(m-1)` (QD2-L2), used for `m = 1, …, d-1`. -/
noncomputable def coneU (d : ℕ) (ell : ℕ → ℝ) (m : ℕ) : ℝ :=
  coneP d ell (m + 1) - 2 * coneP d ell m + coneP d ell (m - 1)

/-- The DKZ multiplier vector `v_m = 2 csc(π m/(2d))`. -/
noncomputable def coneV (d : ℕ) (m : ℕ) : ℝ :=
  2 / Real.sin (π * m / (2 * d))

/-- A cell vector: `ℓ_r ≥ 0` for `r < d` and `∑_{r<d} ℓ_r = d`. -/
def IsConeCell (d : ℕ) (ell : ℕ → ℝ) : Prop :=
  (∀ r < d, 0 ≤ ell r) ∧ ∑ r ∈ Finset.range d, ell r = d

/-- **CONE_d.** The DKZ vector `v` lies in the convex cone generated by the cell directions `u^ℓ`:
there are finitely many cells `ℓ^(k)` and weights `λ_k ≥ 0` with `∑_k λ_k u^{ℓ^(k)}_m = v_m` for every
`m = 1, …, d-1`. -/
def ConeCert (d : ℕ) : Prop :=
  ∃ (K : ℕ) (ell : Fin K → ℕ → ℝ) (lam : Fin K → ℝ),
    (∀ k, IsConeCell d (ell k)) ∧ (∀ k, 0 ≤ lam k) ∧
    ∀ m : ℕ, 1 ≤ m → m ≤ d - 1 → ∑ k, lam k * coneU d (ell k) m = coneV d m

/-- The Clausen series converges absolutely, so `clausen2 θ` is its sum. -/
theorem clausen2_summable (θ : ℝ) :
    Summable fun k : ℕ => Real.sin (((k : ℝ) + 1) * θ) / ((k : ℝ) + 1) ^ 2 := by
  have h : Summable fun k : ℕ => 1 / ((k : ℝ) + 1) ^ 2 := by
    have := (summable_nat_add_iff 1).mpr (Real.summable_one_div_nat_pow.mpr one_lt_two)
    simpa [Nat.cast_add, Nat.cast_one] using this
  refine Summable.of_norm_bounded h fun k => ?_
  rw [Real.norm_eq_abs, abs_div, abs_of_pos (by positivity : (0 : ℝ) < ((k : ℝ) + 1) ^ 2)]
  exact div_le_div_of_nonneg_right (Real.abs_sin_le_one _) (by positivity)

theorem clausen2_hasSum (θ : ℝ) :
    HasSum (fun k : ℕ => Real.sin (((k : ℝ) + 1) * θ) / ((k : ℝ) + 1) ^ 2) (clausen2 θ) :=
  (clausen2_summable θ).hasSum

end OQP27
