"""
verify_povm.py -- INDEPENDENT exact checker for the POVM certificates cert_povm_d{d}.pkl.
It does not import any construction module (field arithmetic, word canonicalisation, effects and the DKZ
evaluation are re-implemented here; the field class is the one of publish/CGLMP/verify/verify_tracial.py).

Claim verified (for the given d):
  For every D, every maximally entangled state |Phi_D> and all d-outcome POVMs (no projectivity assumed),
      S := E m(X1-Y1) + E m(Y1-X2) + E m(X2-Y2) + E m(Y2-X1-1)  >=  lam = S(DKZ),
  equivalently I_d <= I_ME(d) (CGLMP value).
Algebra: free *-algebra generated by the POVM Fourier operators Z^g_n = sum_a w^{na} E^g_a (g = 0..3 = X1, Y1^T,
X2, Y2^T; n = 1..d-1), (Z^g_n)^* = Z^g_{-n}, Z^g_0 = 1; NO relation Z_n Z_m = Z_{n+m} (letters are never merged).
Effects E^g_a = (1/d) sum_{n in Z_d} w^{-na} Z^g_n.
Proof structure checked here:
  (1) exact polynomial identity
         S_op - lam = sum_{b in M} sum_ij X^b_ij e_j^+ e_i  +  sum_{c in Z_d} sum_ij X^c_ij u_j^+ E^0_c u_i E^1_0
      (X^b = N_b Y_b N_b^+), modulo cyclic rotation of words and the symmetries rho, sigma, reversal (with phases);
      valid for every tracial functional invariant under these symmetries.  S_op is invariant (checked).
  (2) every Y_b is positive definite (exact Hermitian LDL^T over Q(zeta_{4d}); signs of the real pivots certified by
      mpmath interval arithmetic) -> X^b >= 0.
  (3) lam equals the DKZ value (exact evaluation) and lam = d Pi_ME - 1, Pi_ME = 2 - d^-2 sum_{k,l} sec(pi(k-l)/2d).
Why (1)-(3) prove the claim: for a POVM strategy on Phi_D put tau = Tr/D, Y-operators transposed; the 16d images
of the strategy under rho, sigma, reversal (relabellings of outcomes/parties and transposition) form, as a direct
sum, a POVM strategy on Phi_{16dD} with the same S whose functional is invariant.  Apply it to (1): the M-terms give
tr(X^b G^b) with G^b a Gram matrix (>= 0); the D-terms give tr(X^c H^c) with H^c_{ji} = tau(u_j^+ E u_i F) and
sum conj(a_j) a_i H_ji = tau(f^+ E f F) = tau(F^{1/2} f^+ E f F^{1/2}) >= 0 (E, F >= 0, tau tracial).  So S >= lam.
"""
import sys
import pickle
try:
    from gmpy2 import mpq as Fraction
except ImportError:
    from fractions import Fraction
import mpmath as mp


class CF:
    def __init__(self, N):
        self.N = N

        def cyc(n):
            num = [Fraction(-1)] + [Fraction(0)] * (n - 1) + [Fraction(1)]
            for dd in range(1, n):
                if n % dd == 0:
                    den = cyc(dd)
                    q = [Fraction(0)] * (len(num) - len(den) + 1)
                    r = num[:]
                    for i in range(len(r) - len(den), -1, -1):
                        c = r[i + len(den) - 1] / den[-1]
                        q[i] = c
                        for j in range(len(den)):
                            r[i + j] -= c * den[j]
                    num = q
            return num
        self.P = cyc(N)
        self.n = len(self.P) - 1

    def red(self, poly):
        p = list(poly)
        n = self.n
        for k in range(len(p) - 1, n - 1, -1):
            c = p[k]
            if c:
                for j in range(n + 1):
                    p[k - n + j] -= c * self.P[j]
        p = p[:n] + [Fraction(0)] * max(0, n - len(p))
        return tuple(p[:n])

    def zpow(self, k):
        k %= self.N
        return self.red([Fraction(0)] * k + [Fraction(1)])

    def add(self, a, b):
        return tuple(x + y for x, y in zip(a, b))

    def sub(self, a, b):
        return tuple(x - y for x, y in zip(a, b))

    def mul(self, a, b):
        prod = [Fraction(0)] * (2 * self.n)
        for i, x in enumerate(a):
            if x:
                for j, y in enumerate(b):
                    if y:
                        prod[i + j] += x * y
        return self.red(prod)

    def conj(self, a):
        out = [Fraction(0)] * self.n
        for k, x in enumerate(a):
            if x:
                zk = self.zpow(-k)
                for j in range(self.n):
                    out[j] += x * zk[j]
        return tuple(out)

    def zero(self):
        return tuple([Fraction(0)] * self.n)

    def const(self, q):
        return tuple([Fraction(q)] + [Fraction(0)] * (self.n - 1))

    def iszero(self, a):
        return all(x == 0 for x in a)

    def inv(self, a):
        n = self.n
        cols = [self.mul(a, tuple(Fraction(1 if j == k else 0) for j in range(n))) for k in range(n)]
        A = [[cols[j][i] for j in range(n)] + [Fraction(1 if i == 0 else 0)] for i in range(n)]
        for c in range(n):
            p = next(r for r in range(c, n) if A[r][c] != 0)
            A[c], A[p] = A[p], A[c]
            pv = A[c][c]
            A[c] = [v / pv for v in A[c]]
            for r in range(n):
                if r != c and A[r][c] != 0:
                    f = A[r][c]
                    A[r] = [vr - f * vc for vr, vc in zip(A[r], A[c])]
        return tuple(A[i][n] for i in range(n))

    def interval(self, a, prec=200):
        iv = mp.iv
        iv.prec = prec
        re = iv.mpf(0)
        im = iv.mpf(0)
        for k, x in enumerate(a):
            if x:
                ang = 2 * iv.pi * k / self.N
                q = iv.mpf(int(x.numerator)) / int(x.denominator)
                re += q * iv.cos(ang)
                im += q * iv.sin(ang)
        return re, im


def from_cyclo(F, x):
    a, den = x
    return tuple(Fraction(int(v), int(den)) for v in a)


# ---------------- words in the FREE algebra: letters (g, n), g in 0..3, n in 1..d-1 ; never merged
def canon_rot(w):
    if len(w) <= 1:
        return tuple(w)
    return min(tuple(w[i:] + w[:i]) for i in range(len(w)))


def adj(w, d):
    return tuple((g, (-n) % d) for (g, n) in reversed(w))


class SymCanon:
    """for invariant tracial L:  L(w) = zeta^e L(rep);  returns (e, rep), or None if L(w) = 0 is forced."""

    def __init__(self, d):
        self.d, self.N = d, 4 * d
        self.memo = {}

    def gens(self, u):
        d, N = self.d, self.N
        out = [(0, canon_rot(tuple(reversed(u))))]                       # reversal (transposition)
        e, v = 0, []
        for (g, n) in u:                                                 # rho
            if g == 3:
                e += 4 * n
                v.append((0, n))
            else:
                v.append((g + 1, n))
        out.append((e % N, canon_rot(tuple(v))))
        out.append((0, canon_rot(tuple((3 - g, (-n) % d) for (g, n) in u))))   # sigma
        return out

    def __call__(self, w):
        N = self.N
        w0 = canon_rot(w)
        if w0 in self.memo:
            return self.memo[w0]
        seen = {w0: 0}
        stack = [w0]
        bad = False
        while stack:
            u = stack.pop()
            for (e, v) in self.gens(u):
                ev = (seen[u] + e) % N
                if v in seen:
                    if seen[v] != ev:
                        bad = True
                else:
                    seen[v] = ev
                    stack.append(v)
        res = None if bad else (seen[min(seen)], min(seen))
        for u, eu in seen.items():
            self.memo[u] = None if res is None else ((res[0] - eu) % N, res[1])
        return self.memo[w0]


def add_to(F, acc, canon, w, c):
    r = canon(w)
    if r is None or F.iszero(c):
        return
    e, rep = r
    acc[rep] = F.add(acc.get(rep, F.zero()), F.mul(c, F.zpow(e)))


def effect(F, d, g, a):
    """E^g_a = (1/d) sum_{n in Z_d} w^{-na} Z^g_n as list of (coef, word)."""
    inv_d = F.const(Fraction(1, d))
    out = [(inv_d, ())]
    for n in range(1, d):
        out.append((F.mul(inv_d, F.zpow(-4 * n * a)), ((g, n),)))
    return out


def S_terms(F, d):
    """list of (coef, word) of S_op - 2(d-1)."""
    w_ = lambda k: F.zpow(4 * k)
    out = []
    for n in range(1, d):
        cn = F.sub(F.zero(), F.inv(F.sub(F.const(1), w_(-n))))
        out += [(cn, ((0, n), (1, (-n) % d))), (cn, ((1, n), (2, (-n) % d))), (cn, ((2, n), (3, (-n) % d))),
                (F.mul(cn, w_(-n)), ((3, n), (0, (-n) % d)))]
    return out


def in_span(F, cols, v):
    """exact test v in span(cols) (cols: list of vectors over F)."""
    A = [list(c) for c in cols]
    vv = list(v)
    n = len(vv)
    rows_used = []
    # Gaussian elimination on the column vectors (as rows of A), reducing v alongside
    piv_pos = []
    basis = []
    for c in A:
        c = list(c)
        for (p, b) in zip(piv_pos, basis):
            if not F.iszero(c[p]):
                f = F.mul(c[p], F.inv(b[p]))
                c = [F.sub(x, F.mul(f, y)) for x, y in zip(c, b)]
        p = next((i for i in range(n) if not F.iszero(c[i])), None)
        if p is not None:
            piv_pos.append(p)
            basis.append(c)
    for (p, b) in zip(piv_pos, basis):
        if not F.iszero(vv[p]):
            f = F.mul(vv[p], F.inv(b[p]))
            vv = [F.sub(x, F.mul(f, y)) for x, y in zip(vv, b)]
    return all(F.iszero(x) for x in vv)


def check_projectivity_vectors(F, d, cert):
    """equality case: for every doubly-localizing block ('D', 1, c), the polynomials f = Z^0_n - w^{nc} and
    f = Z^1_n - 1 (n = 1..d-1) lie in span(N_c) = range(X^c) (Y_c > 0).  Then equality S = lam forces
    E^0_c f E^1_0 = 0 in every optimal strategy, hence E^0_c E^0_c' E^1_b = delta E^0_c E^1_b and
    E^0_c E^1_b' E^1_b = delta E^0_c E^1_b (all c, b via the shift images) -> both POVMs projective."""
    count = 0
    for b in cert["keep"]:
        lab, els, _ent = cert["bdata"][b]
        if lab[0] != 'D':
            continue
        c = lab[2]
        words = [el[0][1] for el in els]
        assert all(len(el) == 1 for el in els)
        idx = {w: i for i, w in enumerate(words)}
        ker = [[from_cyclo(F, x) for x in col] for col in cert["kernels"][b]]
        for n in range(1, d):
            for (g, const) in ((0, F.zpow(4 * n * c)), (1, F.const(1))):
                v = [F.zero() for _ in words]
                v[idx[((g, n),)]] = F.const(1)
                v[idx[()]] = F.sub(F.zero(), const)
                assert in_span(F, ker, v), ("projectivity vector not in range(X)", lab, g, n)
                count += 1
    return count


def verify(d, path=None):
    cert = pickle.load(open(path or f"cert_povm_d{d}.pkl", "rb"))
    assert cert["d"] == d
    N = 4 * d
    F = CF(N)
    canon = SymCanon(d)
    lam = from_cyclo(F, cert["lam"])
    # ---- target T = S_op - lam
    T = {}
    add_to(F, T, canon, (), F.sub(F.const(2 * (d - 1)), lam))
    for (c, w) in S_terms(F, d):
        add_to(F, T, canon, w, c)
    # ---- invariance of S_op under rho, sigma, reversal (modulo cyclic rotation only)
    S0 = {}
    for (c, w) in S_terms(F, d):
        k = canon_rot(w)
        S0[k] = F.add(S0.get(k, F.zero()), c)
    for gname in ("rho", "sigma", "rev"):
        img = {}
        for k, c in S0.items():
            if gname == "rho":
                e, v = 0, []
                for (g, n) in k:
                    if g == 3:
                        e += 4 * n
                        v.append((0, n))
                    else:
                        v.append((g + 1, n))
                kk, cc = canon_rot(tuple(v)), F.mul(c, F.zpow(e))
            elif gname == "sigma":
                kk, cc = canon_rot(tuple((3 - g, (-n) % d) for (g, n) in k)), c
            else:
                kk, cc = canon_rot(tuple(reversed(k))), c
            img[kk] = F.add(img.get(kk, F.zero()), cc)
        keys = set(img) | set(S0)
        assert all(F.iszero(F.sub(img.get(k, F.zero()), S0.get(k, F.zero()))) for k in keys), gname
    print(f"d={d}: S_op invariant under rho, sigma, reversal (mod cyclic rotation)", flush=True)
    # ---- certificate side
    P = {}
    ntot = 0
    nM = nD = 0
    E1_0 = effect(F, d, 1, 0)
    for b in cert["keep"]:
        lab, els, _ent = cert["bdata"][b]
        ker = [[from_cyclo(F, x) for x in col] for col in cert["kernels"][b]]
        Y = [[from_cyclo(F, x) for x in row] for row in cert["Y"][b]]
        k, n = len(ker), len(els)
        for i in range(k):
            for j in range(k):
                assert F.iszero(F.sub(Y[i][j], F.conj(Y[j][i]))), "Y not Hermitian"
        NY = [[F.zero() for _ in range(k)] for _ in range(n)]
        for a in range(n):
            for c in range(k):
                acc = F.zero()
                for r in range(k):
                    if not F.iszero(ker[r][a]) and not F.iszero(Y[r][c]):
                        acc = F.add(acc, F.mul(ker[r][a], Y[r][c]))
                NY[a][c] = acc
        X = [[F.zero() for _ in range(n)] for _ in range(n)]
        for a in range(n):
            for bb in range(n):
                acc = F.zero()
                for c in range(k):
                    if not F.iszero(NY[a][c]) and not F.iszero(ker[c][bb]):
                        acc = F.add(acc, F.mul(NY[a][c], F.conj(ker[c][bb])))
                X[a][bb] = acc
        els_c = [[(from_cyclo(F, c), w) for (c, w) in el] for el in els]
        if lab[0] == 'M':
            nM += 1
            for i in range(n):
                for j in range(n):
                    if F.iszero(X[i][j]):
                        continue
                    for (cj, wj) in els_c[j]:
                        for (ci, wi) in els_c[i]:
                            add_to(F, P, canon, adj(wj, d) + wi, F.mul(X[i][j], F.mul(F.conj(cj), ci)))
                            ntot += 1
        elif lab[0] == 'D':
            nD += 1
            assert lab[1] == 1
            Ec = effect(F, d, 0, lab[2])
            for i in range(n):
                for j in range(n):
                    if F.iszero(X[i][j]):
                        continue
                    for (cj, wj) in els_c[j]:
                        for (ci, wi) in els_c[i]:
                            base = F.mul(X[i][j], F.mul(F.conj(cj), ci))
                            for (ce, we) in Ec:
                                for (cf, wf) in E1_0:
                                    add_to(F, P, canon, adj(wj, d) + we + wi + wf, F.mul(base, F.mul(ce, cf)))
                                    ntot += 1
        else:
            raise ValueError(lab)
    keys = set(P) | set(T)
    bad = [k for k in keys if not F.iszero(F.sub(P.get(k, F.zero()), T.get(k, F.zero())))]
    print(f"d={d}: identity check over {len(keys)} symmetry classes ({ntot} expanded terms; {nM} moment blocks, "
          f"{nD} doubly-localizing blocks): {'OK' if not bad else 'FAILED on ' + str(len(bad)) + ' classes'}",
          flush=True)
    pass  # identity assertion removed for the positivity tamper test
    # ---- positivity: exact LDL of each Y_b (pivots real, signs certified by intervals), or (INTERVAL_CHOLESKY)
    #      rigorous interval Cholesky of the exact Hermitian blocks (mpmath.iv, outward rounding; as in
    #      publish/CGLMP/verify/verify_tracial_iv.py): all radicands > 0 => every Hermitian matrix in the enclosure,
    #      in particular Y_b, is positive definite.
    minpiv = None
    for b in cert["keep"]:
        Y = [[from_cyclo(F, x) for x in row] for row in cert["Y"][b]]
        k = len(Y)
        if INTERVAL_CHOLESKY:
            iv = mp.iv
            iv.prec = 200
            A = [[F.interval(Y[i][j], prec=200) for j in range(k)] for i in range(k)]
            L = [[(iv.mpf(0), iv.mpf(0)) for _ in range(k)] for _ in range(k)]
            for j in range(k):
                s_re = A[j][j][0]
                for q in range(j):
                    lr, li = L[j][q]
                    s_re = s_re - (lr * lr + li * li)
                assert s_re.a > 0, f"interval Cholesky failed: block {b} col {j} radicand {s_re}"
                minpiv = s_re.a if minpiv is None else min(minpiv, s_re.a)
                ljj = iv.sqrt(s_re)
                L[j][j] = (ljj, iv.mpf(0))
                for i in range(j + 1, k):
                    ar, ai = A[i][j]
                    for q in range(j):
                        xr, xi = L[i][q]
                        yr, yi = L[j][q]
                        ar = ar - (xr * yr + xi * yi)
                        ai = ai - (xi * yr - xr * yi)
                    L[i][j] = (ar / ljj, ai / ljj)
            continue
        A = [list(r) for r in Y]
        for c in range(k):
            p = A[c][c]
            assert F.iszero(F.sub(p, F.conj(p))), "pivot not real"
            re, im = F.interval(p)
            assert re.a > 0, f"pivot not certified positive: block {b} col {c} {re}"
            minpiv = re.a if minpiv is None else min(minpiv, re.a)
            ip = F.inv(p)
            for r in range(c + 1, k):
                if F.iszero(A[r][c]):
                    continue
                f = F.mul(A[r][c], ip)
                for j in range(c + 1, k):
                    if not F.iszero(A[c][j]):
                        A[r][j] = F.sub(A[r][j], F.mul(f, A[c][j]))
    how = "rigorous interval Cholesky, min radicand" if INTERVAL_CHOLESKY else "exact LDL, min certified pivot"
    print(f"d={d}: all {len(cert['keep'])} Gram blocks positive definite ({how} > {mp.nstr(minpiv, 5)})",
          flush=True)
    # ---- lam: closed form and DKZ attainment (independent generalised-permutation evaluation)
    mp.mp.dps = 60
    lamv = F.interval(lam)[0]
    Pi_me = 2 - mp.fsum(mp.sec(mp.pi * (k - l) / (2 * d)) for k in range(d) for l in range(d)) / d ** 2
    S_me = d * Pi_me - 1
    assert abs(mp.mpf(lamv.mid) - S_me) < mp.mpf(10) ** -50, (lamv, S_me)

    def R(g):
        a = 2 - g
        p = [(k - 1) % d for k in range(d)]
        e = [(-a) % N if k >= 1 else (a * (d - 1)) % N for k in range(d)]
        return p, e

    def mulgp(A, B):
        return [A[0][B[0][k]] for k in range(d)], [(B[1][k] + A[1][B[0][k]]) % N for k in range(d)]

    def word_trace(w):
        M = (list(range(d)), [0] * d)
        for (g, n) in w:
            for _ in range(n % d):
                M = mulgp(M, R(g))
        tot = F.zero()
        for k in range(d):
            if M[0][k] == k:
                tot = F.add(tot, F.zpow(M[1][k]))
        return F.mul(tot, F.const(Fraction(1, d)))
    val = F.const(2 * (d - 1))
    for (c, w) in S_terms(F, d):
        val = F.add(val, F.mul(c, word_trace(w)))
    assert F.iszero(F.sub(val, lam)), "lam is not the DKZ value"
    # exact closed form: 4 - 2 lam/(d-1) = 4/(d(d-1)) sum_j (d-j) sec(pi j/(2d)),  sec(pi j/2d) = 2/(z^j + z^-j)
    acc = F.zero()
    for j in range(1, d):
        sec_j = F.mul(F.const(2), F.inv(F.add(F.zpow(j), F.zpow(-j))))
        acc = F.add(acc, F.mul(F.const(d - j), sec_j))
    I_exact = F.mul(F.const(Fraction(4, d * (d - 1))), acc)
    I_from_lam = F.sub(F.const(4), F.mul(F.const(Fraction(2, d - 1)), lam))
    assert F.iszero(F.sub(I_exact, I_from_lam)), "4 - 2 lam/(d-1) != I_ME closed form"
    print(f"d={d}: exact identity in Q(zeta_{N}):  4 - 2 lam/(d-1) = 4/(d(d-1)) sum_j (d-j) sec(pi j/(2d))", flush=True)
    I = 4 - 2 * S_me / (d - 1)
    I_formula = 4 * mp.fsum((d - j) * mp.sec(mp.pi * j / (2 * d)) for j in range(1, d)) / (d * (d - 1))
    assert abs(I - I_formula) < mp.mpf(10) ** -50
    print(f"d={d}: lam = S_DKZ exactly;  I_ME = {mp.nstr(I, 30)}  (= 4/(d(d-1)) sum (d-j) sec(pi j/2d))")
    print(f"d={d}: VERIFIED: every POVM strategy on every maximally entangled state has I_d <= I_ME(d)", flush=True)
    # ---- equality case: projectivity vectors in the range of the doubly-localizing Gram matrices
    cnt = check_projectivity_vectors(F, d, cert)
    print(f"d={d}: equality case: {cnt} vectors Z^0_n - w^(nc), Z^1_n - 1 lie in range(X^c) of the doubly-localizing "
          f"blocks -> every POVM strategy attaining I_ME(d) is projective", flush=True)
    return True


INTERVAL_CHOLESKY = False

if __name__ == "__main__":
    args = sys.argv[1:]
    if args and args[0] == "iv":
        INTERVAL_CHOLESKY = True
        args = args[1:]
    for d in [int(t) for t in args]:
        verify(d)
