"""
exact_povm.py -- exact data over Q(zeta), zeta = exp(2 pi i/(4d)), for the symmetry-reduced POVM relaxation of
CGLMP_d on maximally entangled states that is used for the certificates (see povm_sdp.py for the float version).

Free *-algebra generated by the POVM Fourier operators Z^g_n (g = 0..3 chain order X1, Y1, X2, Y2; n = 1..d-1),
(Z^g_n)^* = Z^g_{-n}; NO other relation.  Effects E^g_a = (1/d) sum_{n in Z_d} w^{-n a} Z^g_n (Z^g_0 = 1), w = zeta^4.
Blocks:
  ('M', q, t): moment blocks over W_adj = {1} u {Z^g_n} u {Z^g_n Z^h_m : h - g = +-1 mod 4},
               symmetry-adapted (charge q, rho-eigenvalue zeta^{q + d t});  entry (i,j) = L(el_i^* el_j);
  ('D', 1, c): doubly-localizing blocks, entry (i,j) = L(u_i^* E^0_c u_j E^1_0), u in W1 = {1} u {Z^g_n}, c in Z_d.
Objective S = 2(d-1) + sum_n c_n [L(Z0n Z1-n) + L(Z1n Z2-n) + L(Z2n Z3-n) + w^-n L(Z3n Z0-n)], c_n = -1/(1-w^-n).
Exact DKZ value S_DKZ and exact kernels of every block at the symmetrised DKZ functional (complementary slackness).
Output exact_povm_d{d}.pkl in the format used by cert_povm.py.
"""
import sys
import time
import pickle
import itertools
from cyclo import Field


def cyc(w):
    if len(w) <= 1:
        return tuple(w)
    return min(tuple(w[i:] + w[:i]) for i in range(len(w)))


class ExactSetup:
    def __init__(self, d):
        self.d = d
        self.N = 4 * d
        self.F = Field(self.N)
        self.cache = {}
        self.classes = {}
        self.nvar = 0
        self.var_info = []

    def dagger(self, w):
        d = self.d
        return tuple((g, (-n) % d) for (g, n) in reversed(w))

    def rho(self, w):
        e = 0
        out = []
        for (g, n) in w:
            if g == 3:
                e += 4 * n
                out.append((0, n))
            else:
                out.append((g + 1, n))
        return e % self.N, tuple(out)

    def sigma(self, w):
        d = self.d
        return 0, tuple((3 - g, (-n) % d) for (g, n) in w)

    def orbit(self, w):
        N = self.N
        start = cyc(w)
        seen = {start: 0}
        stack = [start]
        bad = False
        while stack:
            u = stack.pop()
            eu = seen[u]
            cands = [(0, cyc(tuple(reversed(u))))]
            e2, u2 = self.rho(u)
            cands.append((e2, cyc(u2)))
            e3, u3 = self.sigma(u)
            cands.append((e3, cyc(u3)))
            for (e, v) in cands:
                ev = (eu + e) % N
                if v in seen:
                    if seen[v] != ev:
                        bad = True
                else:
                    seen[v] = ev
                    stack.append(v)
        return seen, bad

    def moment(self, w):
        """L(w) as dict var -> F coefficient; var -1 = constant."""
        F, N = self.F, self.N
        key = cyc(w)
        if key in self.cache:
            return self.cache[key]
        orb, bad = self.orbit(key)
        kd = cyc(self.dagger(key))
        orb_d, bad_d = self.orbit(kd)
        if bad or bad_d:
            self.cache[key] = {}
            return {}
        rep = min(set(orb) | set(orb_d))
        if rep == ():
            res = {-1: F.z(orb[()]) if () in orb else F.z(-orb_d[()])}
            self.cache[key] = res
            return res
        cls = self.classes.get(rep)
        if cls is None:
            rd = cyc(self.dagger(rep))
            orb_rd, _ = self.orbit(rd)
            if rep in orb_rd:
                k = orb_rd[rep] % N
                f = F.i_unit() if k == (2 * self.d) % N else F.add(F.one, F.z(-k))
                v = self.nvar
                self.nvar += 1
                self.var_info.append((rep, 'real'))
                cls = ('real', v, f)
            else:
                v1, v2 = self.nvar, self.nvar + 1
                self.nvar += 2
                self.var_info.append((rep, 're'))
                self.var_info.append((rep, 'im'))
                cls = ('cplx', v1, v2)
            self.classes[rep] = cls
        Lrep = {cls[1]: cls[2]} if cls[0] == 'real' else {cls[1]: F.one, cls[2]: F.i_unit()}
        if rep in orb:
            ph = F.z(orb[rep])
            res = {v: F.mul(ph, c) for v, c in Lrep.items()}
        else:
            ph = F.z(-orb_d[rep])
            res = {v: F.mul(ph, F.conj(c)) for v, c in Lrep.items()}
        self.cache[key] = res
        return res

    # polynomials: list of (F coef, word)
    def effect(self, g, a):
        F, d = self.F, self.d
        inv_d = F.from_int(1, d)
        p = [(inv_d, ())]
        for n in range(1, d):
            p.append((F.mul(inv_d, F.z(-4 * n * a)), ((g, n),)))
        return p

    def Lpoly_prod(self, parts):
        """L(prod of polys) as dict var -> coef."""
        F = self.F
        acc = {}
        for combo in itertools.product(*parts):
            c = F.one
            w = ()
            for (cc, ww) in combo:
                c = F.mul(c, cc)
                w = w + ww
            if F.is_zero(c):
                continue
            for v, mc in self.moment(w).items():
                acc[v] = F.add(acc.get(v, F.zero), F.mul(c, mc))
        return {v: c for v, c in acc.items() if not F.is_zero(c)}

    def pdag(self, p):
        return [(self.F.conj(c), self.dagger(w)) for (c, w) in p]

    def words_adj(self):
        d = self.d
        letters = [(g, n) for g in range(4) for n in range(1, d)]
        ws = [()] + [(l,) for l in letters]
        for l1 in letters:
            for l2 in letters:
                if (l2[0] - l1[0]) % 4 in (1, 3):
                    ws.append((l1, l2))
        return ws

    def moment_blocks(self):
        F, d, N = self.F, self.d, self.N
        bysector = {}
        for u in self.words_adj():
            q = sum(n for g, n in u) % d
            bysector.setdefault(q, []).append(u)
        out = []
        for q, wl in sorted(bysector.items()):
            orbits, done = [], set()
            for u in wl:
                if u in done:
                    continue
                orb = []
                e, cur = 0, u
                for k in range(4):
                    orb.append((e, cur))
                    done.add(cur)
                    e2, cur = self.rho(cur)
                    e = (e + e2) % N
                orbits.append(orb)
            for t in range(4):
                mu = (q + d * t) % N
                els = []
                for orb in orbits:
                    if orb[0][1] == ():
                        if mu == 0:
                            els.append([(F.one, ())])
                        continue
                    els.append([(F.z(e - k * mu), wd) for k, (e, wd) in enumerate(orb)])
                if els:
                    out.append((('M', q, t), els))
        return out

    def objective(self):
        F, d = self.F, self.d
        acc = {-1: F.from_int(2 * (d - 1))}
        for n in range(1, d):
            cn = F.neg(F.inv(F.sub(F.one, F.z(-4 * n))))
            terms = [(cn, ((0, n), (1, (-n) % d))), (cn, ((1, n), (2, (-n) % d))),
                     (cn, ((2, n), (3, (-n) % d))), (F.mul(cn, F.z(-4 * n)), ((3, n), (0, (-n) % d)))]
            for (c, w) in terms:
                for v, cc in self.moment(w).items():
                    acc[v] = F.add(acc.get(v, F.zero), F.mul(c, cc))
        for v, c in acc.items():
            assert F.is_real(c), ("objective coefficient not real", v)
        const = acc.pop(-1)
        return {v: c for v, c in acc.items() if not F.is_zero(c)}, const


# ---------------- exact DKZ strategy: generalised permutation matrices  M|k> = zeta^{e[k]} |p[k]>
def gp_mul(A, B, N):
    pA, eA = A
    pB, eB = B
    return ([pA[pB[k]] for k in range(len(pB))], [(eB[k] + eA[pB[k]]) % N for k in range(len(pB))])


def gp_pow(A, n, d, N):
    n %= d
    R = (list(range(d)), [0] * d)
    for _ in range(n):
        R = gp_mul(A, R, N)
    return R


def gp_transpose(A, N):
    p, e = A
    d = len(p)
    pt, et = [0] * d, [0] * d
    for k in range(d):
        pt[p[k]] = k
        et[p[k]] = e[k]
    return (pt, et)


def dkz(d):
    """clock unitaries R_g = sum_a w^a P^g_a of the DKZ strategy (tau-picture), as in publish/CGLMP builders."""
    N = 4 * d
    R = []
    for g in range(4):
        a = 2 - g
        p = [(k - 1) % d for k in range(d)]
        e = [(-a) % N if k >= 1 else (a * (d - 1)) % N for k in range(d)]
        R.append((p, e))
    return R


def strategy_images(R, d):
    N = 4 * d

    def key(S):
        return tuple((tuple(p), tuple(e)) for (p, e) in S)

    def rho_s(S):
        p0, e0 = S[0]
        return [S[1], S[2], S[3], (p0, [(x + 4) % N for x in e0])]

    def sigma_s(S):
        inv = lambda A: gp_pow(A, d - 1, d, N)
        return [inv(S[3]), inv(S[2]), inv(S[1]), inv(S[0])]

    def rev_s(S):
        return [gp_transpose(A, N) for A in S]
    seen = {key(R): R}
    stack = [R]
    while stack:
        S = stack.pop()
        for T in (rho_s(S), sigma_s(S), rev_s(S)):
            k = key(T)
            if k not in seen:
                seen[k] = T
                stack.append(T)
    return list(seen.values())


def dense_of_gp(F, A, d):
    p, e = A
    M = [[F.zero] * d for _ in range(d)]
    for k in range(d):
        M[p[k]][k] = F.z(e[k])
    return M


def mat_mul(F, A, B):
    n = len(A)
    out = [[F.zero] * n for _ in range(n)]
    for i in range(n):
        for k in range(n):
            a = A[i][k]
            if F.is_zero(a):
                continue
            rowB = B[k]
            for j in range(n):
                if not F.is_zero(rowB[j]):
                    out[i][j] = F.add(out[i][j], F.mul(a, rowB[j]))
    return out


def mat_add(F, A, B):
    return [[F.add(a, b) for a, b in zip(ra, rb)] for ra, rb in zip(A, B)]


def mat_scal(F, A, c):
    return [[F.mul(a, c) for a in r] for r in A]


def eval_poly(F, poly, S, d, N):
    """poly (list of (coef, word)) evaluated at strategy S (Z^g_n = R_g^n): dense matrix."""
    out = [[F.zero] * d for _ in range(d)]
    for (c, w) in poly:
        M = (list(range(d)), [0] * d)
        for (g, n) in w:
            M = gp_mul(M, gp_pow(S[g], n, d, N), N)
        p, e = M
        for k in range(d):
            out[p[k]][k] = F.add(out[p[k]][k], F.mul(c, F.z(e[k])))
    return out


def nullspace(F, rows, ncols):
    """rows: list of dict col -> F. basis (list of F vectors) of {x : row.x = 0 for all rows}."""
    R = [dict(r) for r in rows if r]
    pivots, prow = [], []
    for c in range(ncols):
        idx = None
        for i, r in enumerate(R):
            if c in r and not F.is_zero(r[c]):
                idx = i
                break
        if idx is None:
            continue
        r = R.pop(idx)
        inv = F.inv(r[c])
        r = {k: F.mul(v, inv) for k, v in r.items()}
        newR = []
        for s in R:
            if c in s:
                f = s[c]
                t = dict(s)
                for k, v in r.items():
                    t[k] = F.sub(t.get(k, F.zero), F.mul(f, v))
                t = {k: v for k, v in t.items() if not F.is_zero(v)}
                if t:
                    newR.append(t)
            else:
                newR.append(s)
        R = newR
        for j in range(len(prow)):
            s = prow[j]
            if c in s:
                f = s[c]
                t = dict(s)
                for k, v in r.items():
                    t[k] = F.sub(t.get(k, F.zero), F.mul(f, v))
                prow[j] = {k: v for k, v in t.items() if not F.is_zero(v)}
        pivots.append(c)
        prow.append(r)
    free = [c for c in range(ncols) if c not in pivots]
    basis = []
    for fc in free:
        x = [F.zero] * ncols
        x[fc] = F.one
        for pc, r in zip(pivots, prow):
            if fc in r:
                x[pc] = F.neg(r[fc])
        basis.append(x)
    return basis


def build_all(d, verbose=True):
    t0 = time.time()
    st = ExactSetup(d)
    F, N = st.F, st.N
    bdata = []
    # moment blocks
    for (lab, els) in st.moment_blocks():
        n = len(els)
        dags = [st.pdag(e) for e in els]
        ent = {}
        for i in range(n):
            for j in range(i, n):
                ent[(i, j)] = st.Lpoly_prod([dags[i], els[j]])
        bdata.append((lab, els, ent))
    if verbose:
        print(f"d={d}: {len(bdata)} moment blocks sizes {[len(b[1]) for b in bdata]} nvar={st.nvar} "
              f"[{time.time() - t0:.1f}s]", flush=True)
    # doubly localizing blocks (h = 1)
    W1 = [[(F.one, ())]] + [[(F.one, ((g, n),))] for g in range(4) for n in range(1, d)]
    Y = st.effect(1, 0)
    for c in range(d):
        X = st.effect(0, c)
        n = len(W1)
        ent = {}
        for i in range(n):
            ui_d = st.pdag(W1[i])
            for j in range(i, n):
                ent[(i, j)] = st.Lpoly_prod([ui_d, X, W1[j], Y])
        bdata.append((('D', 1, c), W1, ent))
    obj, const = st.objective()
    if verbose:
        print(f"d={d}: total {len(bdata)} blocks, nvar={st.nvar} [{time.time() - t0:.1f}s]", flush=True)
    # exact DKZ value
    R = dkz(d)
    val = F.from_int(2 * (d - 1))
    inv_d = F.from_int(1, d)

    def tau_word(w):
        M = eval_poly(F, [(F.one, w)], R, d, N)
        tr = F.zero
        for k in range(d):
            tr = F.add(tr, M[k][k])
        return F.mul(tr, inv_d)
    for n in range(1, d):
        cn = F.neg(F.inv(F.sub(F.one, F.z(-4 * n))))
        terms = [(cn, ((0, n), (1, (-n) % d))), (cn, ((1, n), (2, (-n) % d))),
                 (cn, ((2, n), (3, (-n) % d))), (F.mul(cn, F.z(-4 * n)), ((3, n), (0, (-n) % d)))]
        for (c, w) in terms:
            val = F.add(val, F.mul(c, tau_word(w)))
    assert F.is_real(val)
    if verbose:
        print(f"   S_DKZ = {F.to_cfloat(val).real:.15f} [{time.time() - t0:.1f}s]", flush=True)
    # kernels at all DKZ images
    imgs = strategy_images(R, d)
    kernels = []
    for (lab, els, ent) in bdata:
        rows = []
        for S in imgs:
            if lab[0] == 'M':
                mats = [eval_poly(F, el, S, d, N) for el in els]
            else:
                c = lab[2]
                Xm = eval_poly(F, st.effect(0, c), S, d, N)
                Ym = eval_poly(F, st.effect(1, 0), S, d, N)
                mats = [mat_mul(F, mat_mul(F, Xm, eval_poly(F, el, S, d, N)), Ym) for el in els]
            for r in range(d):
                for cc in range(d):
                    row = {j: mats[j][r][cc] for j in range(len(els)) if not F.is_zero(mats[j][r][cc])}
                    if row:
                        rows.append(row)
        kernels.append(nullspace(F, rows, len(els)))
    if verbose:
        print(f"   images={len(imgs)} kernel dims {[len(k) for k in kernels]} [{time.time() - t0:.1f}s]", flush=True)
    return dict(d=d, N=N, st_nvar=st.nvar, var_info=st.var_info, bdata=bdata, obj=obj, const=const,
                S_dkz=val, kernels=kernels)


if __name__ == "__main__":
    for d in [int(t) for t in sys.argv[1:]]:
        data = build_all(d)
        data["wordset"] = "adjacent pairs + doubly-localizing (E^0_c, E^1_0)"
        with open(f"exact_povm_d{d}.pkl", "wb") as fh:
            pickle.dump(data, fh)
