"""
povm_sdp.py -- tracial moment relaxation (Lang-Vertesi-Navascues type, J. Phys. A 47, 424029, Def. 13) of
CGLMP_d on maximally entangled states with GENERAL POVMs, symmetry reduced.

Algebra.  Four d-outcome POVMs in chain order g = 0: X1 (Alice x=0), 1: Y1 (Bob y=0, transposed), 2: X2, 3: Y2.
Fourier operators Z^g_n = sum_a w^{n a} E^g_a, n in Z_d, Z^g_0 = 1, (Z^g_n)^* = Z^g_{-n}, w = exp(2 pi i/d).
The Z^g_n (n = 1..d-1) generate the FREE *-algebra (no relation Z_n Z_m = Z_{n+m}: that would be projectivity).
Letter (g, n) = Z^g_n; word = tuple of letters (NO reduction).
E^g_a = (1/d) sum_n w^{-n a} Z^g_n.

Relaxation (level 2):
  L linear on words of length <= 4, L(1) = 1, tracial (cyclic), L(w^*) = conj L(w);
  (M)  [L(u^* v)]_{u,v in W2} >= 0,  W2 = words of length <= 2;
  (Loc) [L(u^* E v)]_{u,v in W1} >= 0 for every effect E   (W1 = words of length <= 1);
  (Dbl) [L(u^* X v Y)]_{u,v in W1} >= 0 for every pair of effects X, Y  (tau(f^* X f Y) >= 0 for X, Y >= 0).
  WLOG L invariant under the symmetry group generated by
     rho:   (g, n) -> (g+1, n) (g < 3),  (3, n) -> w^n (0, n)      [chain rotation + outcome shift]
     sigma: (g, n) -> (3-g, -n)                                     [reflection + outcome negation]
     rev:   w -> reversed word                                      [transposition of all operators]
  (all three map POVM strategies on Phi_D to POVM strategies on Phi_D and fix the objective).
  rho^4 = global outcome shift (charge): L(w) = 0 unless sum of n's = 0 mod d.
Objective (verify_tracial.py convention):  S = 2(d-1) + sum_n c_n [L(Z0n Z1-n) + L(Z1n Z2-n) + L(Z2n Z3-n)
    + w^{-n} L(Z3n Z0-n)],  c_n = -1/(1 - w^{-n});   S = d Pi - 1,  I = 4 - 2 S/(d-1).   minimise S.
Reductions used: charge/rho-sector block diagonalisation of (M); (Loc) only for E^0_0 and (Dbl) only for
(X, Y) = (E^0_c, E^h_0), c in Z_d, h in 0..3 (all others are unitarily equivalent under the symmetry).
"""
import sys
import time
import itertools
import numpy as np
import scipy.sparse as sp


class Setup:
    def __init__(self, d):
        self.d = d
        self.N = 4 * d
        self.zeta = np.exp(2j * np.pi / self.N)
        self.cache = {}
        self.classes = {}
        self.nvar = 0
        self.var_info = []

    def z(self, k):
        return self.zeta ** (k % self.N)

    # ---- symmetry actions on words: return (exponent of zeta, word); L(w) = zeta^e L(word)
    def rho(self, w):
        e = 0
        out = []
        for (g, n) in w:
            if g == 3:
                e += 4 * n
                out.append((0, n))
            else:
                out.append((g + 1, n))
        return e % self.N, tuple(out)

    def sigma(self, w):
        d = self.d
        return 0, tuple((3 - g, (-n) % d) for (g, n) in w)

    @staticmethod
    def cyc(w):
        if len(w) <= 1:
            return tuple(w)
        return min(tuple(w[i:] + w[:i]) for i in range(len(w)))

    def dagger(self, w):
        d = self.d
        return tuple((g, (-n) % d) for (g, n) in reversed(w))

    def orbit(self, w):
        N = self.N
        start = self.cyc(w)
        seen = {start: 0}
        stack = [start]
        bad = False
        while stack:
            u = stack.pop()
            eu = seen[u]
            cands = [(0, self.cyc(tuple(reversed(u))))]
            e2, u2 = self.rho(u)
            cands.append((e2, self.cyc(u2)))
            e3, u3 = self.sigma(u)
            cands.append((e3, self.cyc(u3)))
            for (e, v) in cands:
                ev = (eu + e) % N
                if v in seen:
                    if seen[v] != ev:
                        bad = True
                else:
                    seen[v] = ev
                    stack.append(v)
        return seen, bad

    def moment(self, w):
        """L(w) as dict var -> complex coefficient ; var -1 = constant term."""
        N = self.N
        key = self.cyc(w)
        if key in self.cache:
            return self.cache[key]
        orb, bad = self.orbit(key)
        kd = self.cyc(self.dagger(key))
        orb_d, bad_d = self.orbit(kd)
        if bad or bad_d:
            self.cache[key] = {}
            return {}
        rep = min(set(orb) | set(orb_d))
        if rep == ():
            res = {-1: self.z(orb[()]) if () in orb else np.conj(self.z(orb_d[()]))}
            self.cache[key] = res
            return res
        cls = self.classes.get(rep)
        if cls is None:
            rd = self.cyc(self.dagger(rep))
            orb_rd, _ = self.orbit(rd)
            if rep in orb_rd:
                k = orb_rd[rep] % N            # conj L(rep) = L(rd) = zeta^k L(rep)
                f = 1j if k == (2 * self.d) % N else 1 + self.z(-k)
                v = self.nvar
                self.nvar += 1
                self.var_info.append((rep, 'real', f))
                cls = ('real', v, f)
            else:
                v1, v2 = self.nvar, self.nvar + 1
                self.nvar += 2
                self.var_info.append((rep, 're', 1.0))
                self.var_info.append((rep, 'im', 1j))
                cls = ('cplx', v1, v2)
            self.classes[rep] = cls
        Lrep = {cls[1]: cls[2]} if cls[0] == 'real' else {cls[1]: 1.0, cls[2]: 1j}
        if rep in orb:
            ph = self.z(orb[rep])
            res = {v: ph * c for v, c in Lrep.items()}
        else:
            # L(key) = conj(L(kd)) = conj(zeta^{orb_d[rep]} L(rep))
            ph = np.conj(self.z(orb_d[rep]))
            res = {v: ph * np.conj(c) for v, c in Lrep.items()}
        self.cache[key] = res
        return res

    # ---- polynomial helpers: poly = dict word -> complex coefficient
    def L(self, poly):
        acc = {}
        for w, c in poly.items():
            if c == 0:
                continue
            for v, cc in self.moment(w).items():
                acc[v] = acc.get(v, 0) + c * cc
        return {v: c for v, c in acc.items() if abs(c) > 1e-14}

    def effect(self, g, a):
        """E^g_a = (1/d) sum_n w^{-n a} Z^g_n as poly."""
        d = self.d
        p = {(): 1.0 / d}
        for n in range(1, d):
            p[((g, n),)] = self.z(-4 * n * a) / d
        return p

    @staticmethod
    def pmul(*ps):
        out = {(): 1.0}
        for p in ps:
            new = {}
            for w1, c1 in out.items():
                for w2, c2 in p.items():
                    w = w1 + w2
                    new[w] = new.get(w, 0) + c1 * c2
            out = new
        return out

    def pdag(self, p):
        return {self.dagger(w): np.conj(c) for w, c in p.items()}

    # ---- symmetry-adapted moment blocks
    def words(self, maxlen, adj=False):
        """words of length <= maxlen; adj=True keeps only length-2 words on chain-adjacent generators (g, g+-1)."""
        d = self.d
        letters = [(g, n) for g in range(4) for n in range(1, d)]
        ws = [()]
        for L_ in range(1, maxlen + 1):
            for t in itertools.product(letters, repeat=L_):
                if adj and L_ == 2 and (t[1][0] - t[0][0]) % 4 not in (1, 3):
                    continue
                ws.append(tuple(t))
        return ws

    def moment_blocks(self, maxlen=2, adj=False):
        d, N = self.d, self.N
        ws = self.words(maxlen, adj=adj)
        bysector = {}
        for u in ws:
            q = sum(n for g, n in u) % d
            bysector.setdefault(q, []).append(u)
        out = []
        for q, wl in sorted(bysector.items()):
            orbits, done = [], set()
            for u in wl:
                if u in done:
                    continue
                orb = []
                e, cur = 0, u
                for k in range(4):
                    orb.append((e, cur))
                    done.add(cur)
                    e2, cur = self.rho(cur)
                    e = (e + e2) % N
                orbits.append(orb)
            for t in range(4):
                mu = (q + d * t) % N
                els = []
                for orb in orbits:
                    if orb[0][1] == ():
                        if mu == 0:
                            els.append({(): 1.0})
                        continue
                    el = {}
                    for k, (e, wd) in enumerate(orb):
                        el[wd] = el.get(wd, 0) + self.z(e - k * mu)
                    els.append(el)
                if els:
                    out.append((('M', q, t), els))
        return out

    def block_entries(self, els, mid=None, right=None):
        """entries[(i,j)] = L(el_i^* mid el_j right) as dict var -> coef (i <= j)."""
        n = len(els)
        ent = {}
        dags = [self.pdag(e) for e in els]
        for i in range(n):
            for j in range(i, n):
                parts = [dags[i]]
                if mid is not None:
                    parts.append(mid)
                parts.append(els[j])
                if right is not None:
                    parts.append(right)
                ent[(i, j)] = self.L(self.pmul(*parts))
        return ent


def build(d, maxlen=2, loc=True, dbl=True, dbl_h=(0, 1, 2, 3), verbose=True, adj=False):
    t0 = time.time()
    st = Setup(d)
    blocks = []
    for (lab, els) in st.moment_blocks(maxlen, adj=adj):
        blocks.append((lab, len(els), st.block_entries(els)))
    if verbose:
        print(f"d={d}: {len(blocks)} moment blocks, sizes {[b[1] for b in blocks]} nvar={st.nvar} "
              f"[{time.time() - t0:.1f}s]", flush=True)
    W1 = [{(): 1.0}] + [{((g, n),): 1.0} for g in range(4) for n in range(1, d)]
    if loc:
        E00 = st.effect(0, 0)
        blocks.append((('Loc', 0, 0), len(W1), st.block_entries(W1, mid=E00)))
    if dbl:
        for h in dbl_h:
            for c in range(d):
                X = st.effect(0, c)
                Y = st.effect(h, 0)
                blocks.append((('Dbl', h, c), len(W1), st.block_entries(W1, mid=X, right=Y)))
    # objective
    obj = {}
    const = 2.0 * (d - 1)
    for n in range(1, d):
        cn = -1.0 / (1.0 - st.z(-4 * n))
        terms = [(cn, ((0, n), (1, (-n) % d))), (cn, ((1, n), (2, (-n) % d))),
                 (cn, ((2, n), (3, (-n) % d))), (cn * st.z(-4 * n), ((3, n), (0, (-n) % d)))]
        for (c, w) in terms:
            for v, cc in st.moment(w).items():
                if v < 0:
                    const += (c * cc).real
                else:
                    obj[v] = obj.get(v, 0) + c * cc
    for v, c in obj.items():
        assert abs(c.imag) < 1e-12, ("objective not real", v, c)
    obj = {v: c.real for v, c in obj.items() if abs(c) > 1e-14}
    if verbose:
        print(f"d={d}: total {len(blocks)} blocks, nvar={st.nvar} [{time.time() - t0:.1f}s]", flush=True)
    return st, blocks, obj, const


def dense_blocks(blocks, nvar):
    """for each block: (H0, {v: Hv}) dense complex Hermitian."""
    out = []
    for (lab, n, ent) in blocks:
        H0 = np.zeros((n, n), complex)
        Hv = {}
        for (i, j), dct in ent.items():
            for v, c in dct.items():
                if v < 0:
                    H0[i, j] += c
                    if i != j:
                        H0[j, i] += np.conj(c)
                else:
                    if v not in Hv:
                        Hv[v] = np.zeros((n, n), complex)
                    Hv[v][i, j] += c
                    if i != j:
                        Hv[v][j, i] += np.conj(c)
        out.append((lab, H0, Hv))
    return out


def compact(dblocks, obj, nvar):
    """drop variables that occur in no block (they would be free); returns new blocks, obj, nvar, old->new map."""
    used = sorted(set(v for (_, _, Hv) in dblocks for v in Hv))
    mp_ = {v: i for i, v in enumerate(used)}
    for v in obj:
        assert v in mp_, f"objective variable {v} occurs in no PSD block (unbounded)"
    nb = [(lab, H0, {mp_[v]: H for v, H in Hv.items()}) for (lab, H0, Hv) in dblocks]
    return nb, {mp_[v]: c for v, c in obj.items()}, len(used), used


def solve_clarabel(dblocks, obj, const, nvar, tol=1e-10, verbose=False, maxiter=500):
    """minimise obj.y + const  s.t.  H0 + sum_v y_v Hv >= 0 (complex Hermitian blocks, real embedding)."""
    import clarabel
    dblocks, obj, nvar, used = compact(dblocks, obj, nvar)
    rows, cols, vals, b, cones = [], [], [], [], []
    r0 = 0
    for (lab, H0, Hv) in dblocks:
        n = H0.shape[0]
        is_real = np.abs(H0.imag).max() < 1e-14 and all(np.abs(H.imag).max() < 1e-14 for H in Hv.values())

        def emb(H):
            return H.real if is_real else np.block([[H.real, -H.imag], [H.imag, H.real]])
        E0 = emb(H0)
        Ev = {v: emb(H) for v, H in Hv.items()}
        Nn = E0.shape[0]
        iu = [(I, J) for J in range(Nn) for I in range(J + 1)]
        sc = np.array([1.0 if I == J else np.sqrt(2.0) for (I, J) in iu])
        II = np.array([I for I, J in iu])
        JJ = np.array([J for I, J in iu])
        b.extend(list(sc * E0[II, JJ]))
        for v, H in Ev.items():
            col = -sc * H[II, JJ]
            nz = np.nonzero(np.abs(col) > 1e-15)[0]
            rows.extend(list(r0 + nz))
            cols.extend([v] * len(nz))
            vals.extend(list(col[nz]))
        r0 += len(iu)
        cones.append(clarabel.PSDTriangleConeT(Nn))
    A = sp.csc_matrix((vals, (rows, cols)), shape=(r0, nvar))
    P = sp.csc_matrix((nvar, nvar))
    q = np.zeros(nvar)
    for v, c in obj.items():
        q[v] = c
    settings = clarabel.DefaultSettings()
    settings.verbose = verbose
    settings.tol_gap_abs = tol
    settings.tol_gap_rel = tol
    settings.tol_feas = tol
    settings.tol_ktratio = 1e-9
    settings.max_iter = maxiter
    solver = clarabel.DefaultSolver(P, q, A, np.array(b), cones, settings)
    sol = solver.solve()
    yfull = np.zeros(max(used) + 1 if used else 0)
    yfull[used] = np.array(sol.x)
    return sol.obj_val + const, yfull, sol


def solve_ipm(dblocks, obj, const, nvar, tol=1e-13, maxit=150, verbose=False):
    """in-house HKM interior point (ipm.py, copied from publish/CGLMP/builders): returns dict with
    'obj' (moment value), 'pobj_bound' (SOS/dual value), X (dual Gram blocks), Z (moment blocks), y."""
    import ipm
    dblocks, obj, nvar, used = compact(dblocks, obj, nvar)
    M0 = [H0 for (_, H0, _) in dblocks]
    Ms = [Hv for (_, _, Hv) in dblocks]
    c = np.zeros(nvar)
    for v, cc in obj.items():
        c[v] = cc
    res = ipm.solve(M0, Ms, c, const, tol=tol, maxit=maxit, verbose=verbose)
    yfull = np.zeros(max(used) + 1)
    yfull[used] = res['y']
    res['yfull'] = yfull
    res['labels'] = [lab for (lab, _, _) in dblocks]
    return res


def S_to_I(S, d):
    return 4.0 - 2.0 * S / (d - 1)


def I_ME(d):
    k = np.arange(1, d)
    return 4.0 / (d * (d - 1)) * np.sum((d - k) / np.cos(np.pi * k / (2 * d)))


if __name__ == "__main__":
    d = int(sys.argv[1])
    opts = sys.argv[2:]
    loc = 'noloc' not in opts
    dbl = 'nodbl' not in opts
    dbl_h = (1, 3) if 'ABonly' in opts else (0, 1, 2, 3)
    adj = 'adj' in opts
    t0 = time.time()
    st, blocks, obj, const = build(d, loc=loc, dbl=dbl, dbl_h=dbl_h, adj=adj)
    db = dense_blocks(blocks, st.nvar)
    if 'ipm' in opts:
        res = ipm_res = solve_ipm(db, obj, const, st.nvar)
        S, Sb = res['obj'], res['pobj_bound']
        print(f"d={d} loc={loc} dbl={dbl} h={dbl_h} [ipm]: moment S* = {S:.14f} SOS bound = {Sb:.14f}  "
              f"I* = {S_to_I(Sb, d):.13f}  I_ME = {I_ME(d):.13f}  I*-I_ME = {S_to_I(Sb, d) - I_ME(d):+.3e}  "
              f"rp {res['rp']:.1e} rd {res['rd']:.1e} gap {res['gap']:.1e} [{time.time() - t0:.1f}s]", flush=True)
    else:
        S, y, sol = solve_clarabel(db, obj, const, st.nvar, verbose=False)
        print(f"d={d} loc={loc} dbl={dbl} h={dbl_h}: status {sol.status}  S* = {S:.12f}  I* = {S_to_I(S, d):.12f}  "
              f"I_ME = {I_ME(d):.12f}  I*-I_ME = {S_to_I(S, d) - I_ME(d):+.3e}  [{time.time() - t0:.1f}s]", flush=True)
