"""Write the final certificate files OQP27/Cert*.lean and OQP27/certdata/cert_d*.json from cell specs.
usage: python mkfiles.py <spec.json> <LeanFileStem> [d ...]"""
import sys, json, os
from fractions import Fraction as F
import gencert as G

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def rs(x):
    x = F(x)
    return str(x.numerator) if x.denominator == 1 else f"{x.numerator}/{x.denominator}"


def main():
    spec = json.load(open(sys.argv[1]))
    stem = sys.argv[2]
    ds = [int(a) for a in sys.argv[3:]] if len(sys.argv) > 3 else sorted(int(k) for k in spec)
    os.makedirs(os.path.join(ROOT, "certdata"), exist_ok=True)
    blocks = []
    thms = []
    for d in ds:
        ok, c = G.build(d, 1, spec[str(d)])
        if not ok:
            raise SystemExit(f"d={d}: emulated check FAILED")
        js = dict(d=d, q=1, cells=c['cells'], lam=[rs(x) for x in c['lam']],
                  R=[[rs(x) for x in row] for row in c['R']], eps=rs(c['eps']), beta=rs(c['beta']),
                  emulated_check=dict(max_row_sum=float(c['info']['maxrow']), max_Rres=float(c['info']['maxRr']),
                                      min_certified_weight=float(c['info']['mincol'])))
        with open(os.path.join(ROOT, "certdata", f"cert_d{d}.json"), "w") as fh:
            json.dump(js, fh, indent=1)
        blocks.append(G.lean_cert(c, f"cert{d}"))
        thms.append(d)
    ds_txt = ", ".join(str(d) for d in thms)
    head = f"""import OQP27.CertPipeline

/-!
# CONE_d checked in Lean for d = {ds_txt} (module L4)

Authors: Ansh Mishra, Aryan Senthilkumar.  License: MIT.

For each listed `d` this file contains an explicit certificate (`OQP27.ConeCertificate`: `d - 1` integer cells,
rational approximate weights, a rational approximate inverse `R` of `U Uᵀ`, and the bounds `eps`, `beta`) and the
theorems `OQP27.cert<d>_check : cert<d>.fullCheck = true`, established by kernel evaluation (`decide +kernel`), and
`OQP27.coneCert_<d> : OQP27.ConeCert d` (by `OQP27.ConeCertificate.fullCheck_sound`).  The kernel recomputes all
rigorous enclosures (π, sines, Clausen values, `Ĝ`, the cell directions `u^ℓ`, the vector `v`) and the residual-
correction check.  No `native_decide`, no hypotheses.

The certificate data were generated by `OQP27/certdata/gencert.py` (copies in `OQP27/certdata/cert_d<d>.json`);
they are untrusted input: only the Lean kernel check matters.

Mathematics of CONE_d: `cone-certificates/RESEARCH_LOG.md`, sections 1-4.
-/

namespace OQP27

"""
    body = "\n".join(blocks)
    tail = ""
    for d in thms:
        tail += f"""/-- The complete check of `cert{d}` passes (kernel evaluation). -/
theorem cert{d}_check : cert{d}.fullCheck = true := by decide +kernel

/-- **CONE_{d}**, checked by the Lean kernel. -/
theorem coneCert_{d} : ConeCert {d} := cert{d}.fullCheck_sound cert{d}_check

"""
    tail += "end OQP27\n"
    with open(os.path.join(ROOT, f"{stem}.lean"), "w", encoding="utf-8") as fh:
        fh.write(head + body + "\n" + tail)
    print(f"wrote {stem}.lean for d = {ds_txt}")


if __name__ == "__main__":
    main()
