"""Write a two-stage certificate file OQP27/CertD<d>.lean (see OQP27/CertStaged.lean): the certificate, the literal
table of u-enclosures (exactly as computed by the Lean checker, reproduced by leanemu.py), and the two theorems.
usage (from OQP27/certdata): python mkstaged.py cells_d2_d20.json <d>"""
import sys, json, os
from fractions import Fraction as F
import gencert as G
import leanemu as E

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def rs(x):
    x = F(x)
    return str(x.numerator) if x.denominator == 1 else f"{x.numerator}/{x.denominator}"


def main():
    spec = json.load(open(sys.argv[1]))
    d = int(sys.argv[2])
    ok, c = G.build(d, 1, spec[str(d)])
    if not ok:
        raise SystemExit(f"d={d}: emulated check FAILED")
    gT = E.gTab(d, 1)
    UT = [E.uList(d, gT, n) for n in c['cells']]
    js = dict(d=d, q=1, cells=c['cells'], lam=[rs(x) for x in c['lam']],
              R=[[rs(x) for x in row] for row in c['R']], eps=rs(c['eps']), beta=rs(c['beta']),
              emulated_check=dict(max_row_sum=float(c['info']['maxrow']), max_Rres=float(c['info']['maxRr']),
                                  min_certified_weight=float(c['info']['mincol'])))
    with open(os.path.join(ROOT, "certdata", f"cert_d{d}.json"), "w") as fh:
        json.dump(js, fh, indent=1)
    rows = []
    for col in UT:
        rows.append("[" + ",\n    ".join(f"⟨{rs(I.lo)}, {rs(I.hi)}⟩" for I in col) + "]")
    lit = "[" + ",\n   ".join(rows) + "]"
    head = f"""import OQP27.CertStaged

/-!
# CONE_d checked in Lean for d = {d} (module L4, two-stage check)

Authors: Ansh Mishra, Aryan Senthilkumar.  License: MIT.

The certificate `OQP27.cert{d}` (`{d - 1}` integer cells, rational approximate weights, a rational approximate
inverse `R` of `U Uᵀ`, the bounds `eps`, `beta`), `OQP27.cert{d}_check : cert{d}.fullCheck = true` and
`OQP27.coneCert_{d} : OQP27.ConeCert {d}`.
The check is split in two kernel evaluations (file `CertStaged`, to bound the memory of each): `OQP27.uTable{d}`
proves that the literal table `OQP27.uLit{d}` equals the table of rigorous enclosures of the cell directions
computed by the checker (`cert{d}.uTable`); `OQP27.cert{d}_checkU` runs the rest of the check on it.
Both by `decide +kernel`; no `native_decide`, no hypotheses.

Data generated by `OQP27/certdata/mkstaged.py` (copy in `OQP27/certdata/cert_d{d}.json`); untrusted input.
Mathematics of CONE_d: `cone-certificates/RESEARCH_LOG.md`, sections 1-4.
-/

namespace OQP27

"""
    body = G.lean_cert(c, f"cert{d}")
    body += f"""
/-- Literal table of the enclosures of `u^{{ℓ^(k)}}_m` (one list per cell, `m = 1, …, {d - 1}`). -/
def uLit{d} : List (List QI) :=
  {lit}

/-- Stage 1: the literal table is the table computed by the checker. -/
theorem uTable{d} : cert{d}.uTable = uLit{d} := qiTableEqb_eq (by decide +kernel)

/-- Stage 2: the rest of the check passes on the literal table. -/
theorem cert{d}_checkU : cert{d}.fullCheckU uLit{d} = true := by decide +kernel

/-- The complete check of `cert{d}` passes. -/
theorem cert{d}_check : cert{d}.fullCheck = true :=
  cert{d}.fullCheck_of_fullCheckU uLit{d} uTable{d} cert{d}_checkU

/-- **CONE_{d}**, checked by the Lean kernel. -/
theorem coneCert_{d} : ConeCert {d} := cert{d}.fullCheck_sound cert{d}_check

end OQP27
"""
    with open(os.path.join(ROOT, f"CertD{d}.lean"), "w", encoding="utf-8") as fh:
        fh.write(head + body)
    print(f"wrote CertD{d}.lean")


if __name__ == "__main__":
    main()
